-- ============================================================
-- SQL Migration for Saleen Service App
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- 1. Add missing columns to services table
ALTER TABLE services ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE services ADD COLUMN IF NOT EXISTS category_slug text;
ALTER TABLE services ADD COLUMN IF NOT EXISTS profession text;
ALTER TABLE services ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE services ADD COLUMN IF NOT EXISTS latitude double precision;
ALTER TABLE services ADD COLUMN IF NOT EXISTS longitude double precision;
ALTER TABLE services ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE services ADD COLUMN IF NOT EXISTS owner_id text;
ALTER TABLE services ADD COLUMN IF NOT EXISTS rejection_reason text;

-- Add unique constraint on slug
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'services' AND constraint_name = 'services_slug_key'
  ) THEN
    ALTER TABLE services ADD CONSTRAINT services_slug_key UNIQUE (slug);
  END IF;
END $$;

-- 2. Add missing columns to categories table
ALTER TABLE categories ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS color text DEFAULT 'blue';
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image text;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS description text DEFAULT '';

-- Sync existing category rows: set slug = id where slug is null
UPDATE categories SET slug = id WHERE slug IS NULL;

-- Add unique constraint on categories(slug)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'categories' AND constraint_name = 'categories_slug_key'
  ) THEN
    ALTER TABLE categories ADD CONSTRAINT categories_slug_key UNIQUE (slug);
  END IF;
END $$;

-- 3. Create slider_images table if not exists and add ad columns
CREATE TABLE IF NOT EXISTS slider_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url text NOT NULL DEFAULT '',
  title text NOT NULL DEFAULT '',
  display_date text,
  start_time text,
  end_time text,
  images text[] DEFAULT '{}',
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE slider_images ADD COLUMN IF NOT EXISTS display_date text;
ALTER TABLE slider_images ADD COLUMN IF NOT EXISTS start_time text;
ALTER TABLE slider_images ADD COLUMN IF NOT EXISTS end_time text;
ALTER TABLE slider_images ADD COLUMN IF NOT EXISTS images text[] DEFAULT '{}';
ALTER TABLE slider_images ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE slider_images ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- 4. Enable RLS on services table with policies
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any (to avoid duplicates)
DROP POLICY IF EXISTS "services_select_policy" ON services;
DROP POLICY IF EXISTS "services_insert_policy" ON services;
DROP POLICY IF EXISTS "services_update_policy" ON services;
DROP POLICY IF EXISTS "services_delete_policy" ON services;

-- IMPORTANT: The app uses a device-generated owner_id (localStorage) with
-- anonymous Supabase access. Since auth.uid() is NULL for anonymous users,
-- we cannot rely on auth.uid() for RLS. Instead, we allow reading all
-- services and let the client-side code filter by status and owner_id.
-- This is safe because the app's business logic enforces visibility rules.
CREATE POLICY "services_select_policy" ON services
  FOR SELECT
  USING (true);

-- Policy: Anyone can insert services (they start as pending)
CREATE POLICY "services_insert_policy" ON services
  FOR INSERT
  WITH CHECK (true);

-- Policy: Allow updates to services (admin panel and owner edits)
-- Since we use anonymous access, we allow all updates and rely on
-- client-side authorization for the admin panel.
CREATE POLICY "services_update_policy" ON services
  FOR UPDATE
  USING (true);

-- Policy: Allow deletes (admin panel)
CREATE POLICY "services_delete_policy" ON services
  FOR DELETE
  USING (true);

-- 5. Enable RLS on categories table (public read, admin write)
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "categories_select_policy" ON categories;
DROP POLICY IF EXISTS "categories_insert_policy" ON categories;
DROP POLICY IF EXISTS "categories_update_policy" ON categories;
DROP POLICY IF EXISTS "categories_delete_policy" ON categories;

CREATE POLICY "categories_select_policy" ON categories
  FOR SELECT
  USING (true);

CREATE POLICY "categories_insert_policy" ON categories
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "categories_update_policy" ON categories
  FOR UPDATE
  USING (true);

CREATE POLICY "categories_delete_policy" ON categories
  FOR DELETE
  USING (true);

-- 6. Enable RLS on slider_images table (public read, admin write)
ALTER TABLE slider_images ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "slider_images_select_policy" ON slider_images;
DROP POLICY IF EXISTS "slider_images_insert_policy" ON slider_images;
DROP POLICY IF EXISTS "slider_images_update_policy" ON slider_images;
DROP POLICY IF EXISTS "slider_images_delete_policy" ON slider_images;

CREATE POLICY "slider_images_select_policy" ON slider_images
  FOR SELECT
  USING (true);

CREATE POLICY "slider_images_insert_policy" ON slider_images
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "slider_images_update_policy" ON slider_images
  FOR UPDATE
  USING (true);

CREATE POLICY "slider_images_delete_policy" ON slider_images
  FOR DELETE
  USING (true);

-- 7. Verify: show services columns
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'services'
ORDER BY ordinal_position;