-- ============================================================
-- SQL Migration: نظام التفاعلات والتعليقات للتصفح الاجتماعي
-- (Feed interactions: reactions + per-service comments)
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- (تم تنفيذه فعلياً على القاعدة عبر scripts/_create_feed_tables.cjs)
--
-- ملاحظات:
--  * جدول comments الموجود (جدار "تواصل معنا" العام) لم يُمَس إطلاقاً.
--  * كل تعليق/تفاعل مرتبط بالخدمة (service_id) وبمالك الجهاز (owner_id).
--  * منع التفاعل المكرر لنفس المستخدم على نفس المنشور عبر قيد UNIQUE.
--  * RLS مفعّل على الجدولين مع سياسات مطابقة لنمط جدول comments الحالي.
-- ============================================================

-- ---------- 1) التفاعلات ----------
CREATE TABLE IF NOT EXISTS public.service_reactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id integer NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  owner_id text NOT NULL,
  reaction_type text NOT NULL CHECK (reaction_type IN ('like','love','rose','haha','wow','sad','angry','clap','amazing')),
  created_at timestamptz NOT NULL DEFAULT now(),
  -- تفاعل واحد فقط لكل مستخدم (جهاز) على كل منشور
  CONSTRAINT service_reactions_unique_per_owner UNIQUE (service_id, owner_id)
);

CREATE INDEX IF NOT EXISTS service_reactions_service_id_idx
  ON public.service_reactions (service_id);

ALTER TABLE public.service_reactions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_reactions_select_policy" ON public.service_reactions;
DROP POLICY IF EXISTS "service_reactions_insert_policy" ON public.service_reactions;
DROP POLICY IF EXISTS "service_reactions_update_policy" ON public.service_reactions;
DROP POLICY IF EXISTS "service_reactions_delete_policy" ON public.service_reactions;

-- الجميع يقرأ الأعداد (منشورات عامة).
CREATE POLICY "service_reactions_select_policy" ON public.service_reactions
  FOR SELECT USING (true);

-- الإضافة مسموحة؛ قيد UNIQUE يمنع تكرار تفاعل نفس المستخدم على نفس المنشور.
CREATE POLICY "service_reactions_insert_policy" ON public.service_reactions
  FOR INSERT WITH CHECK (owner_id IS NOT NULL AND length(trim(owner_id)) > 0);

-- تغيير نوع التفاعل (تحديث تفاعله هو فقط).
CREATE POLICY "service_reactions_update_policy" ON public.service_reactions
  FOR UPDATE USING (true) WITH CHECK (owner_id IS NOT NULL AND length(trim(owner_id)) > 0);

-- إلغاء التفاعل.
CREATE POLICY "service_reactions_delete_policy" ON public.service_reactions
  FOR DELETE USING (true);

-- ---------- 2) التعليقات على المنشورات ----------
CREATE TABLE IF NOT EXISTS public.service_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id integer NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  content text NOT NULL,
  owner_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  -- منع التعليق الفارغ على مستوى قاعدة البيانات (بالإضافة إلى التحقق في الواجهة)
  CONSTRAINT service_comments_not_empty CHECK (length(trim(content)) > 0 AND length(content) <= 500)
);

CREATE INDEX IF NOT EXISTS service_comments_service_id_idx
  ON public.service_comments (service_id, created_at);

ALTER TABLE public.service_comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_comments_select_policy" ON public.service_comments;
DROP POLICY IF EXISTS "service_comments_insert_policy" ON public.service_comments;
DROP POLICY IF EXISTS "service_comments_delete_policy" ON public.service_comments;

CREATE POLICY "service_comments_select_policy" ON public.service_comments
  FOR SELECT USING (true);

CREATE POLICY "service_comments_insert_policy" ON public.service_comments
  FOR INSERT WITH CHECK (
    owner_id IS NOT NULL AND length(trim(owner_id)) > 0
    AND length(trim(content)) > 0
  );

CREATE POLICY "service_comments_delete_policy" ON public.service_comments
  FOR DELETE USING (true);

-- ---------- 4) توسيع أنواع التفاعلات المسموحة ----------
-- إضافة rose/haha/angry مع الإبقاء على الأنواع القديمة (clap/amazing) صالحة
-- حتى لا تُكسر البيانات الموجودة. يُنفَّذ بأمان على جدول موجود مسبقاً.
ALTER TABLE public.service_reactions DROP CONSTRAINT IF EXISTS service_reactions_reaction_type_check;
ALTER TABLE public.service_reactions ADD CONSTRAINT service_reactions_reaction_type_check
  CHECK (reaction_type IN ('like','love','rose','haha','wow','sad','angry','clap','amazing'));

-- ---------- 3) إعادة معرف الخدمة المعلقة لصاحبها ----------
-- الخدمة الجديدة (pending) لا يستطيع anon قراءتها عبر SELECT (سياسة RLS)،
-- لكن شريط التفاعل يحتاج الـ id الرقمي الحقيقي. هذه الدالة تعيد المعرف فقط
-- عندما يتطابق (slug + owner_id) معاً — أي لا تكشف شيئاً عن خدمات الأجهزة الأخرى.
CREATE OR REPLACE FUNCTION public.get_own_pending_service_id(p_slug text, p_owner_id text)
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id FROM public.services
  WHERE slug = p_slug AND owner_id = p_owner_id AND status = 'pending'
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.get_own_pending_service_id(text, text) TO anon, authenticated;
