-- ============================================================
-- SQL Migration: "المراسلات والمقترحات" (Contact / Suggestions)
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- 1. Create the messages / suggestions table
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_type text NOT NULL DEFAULT 'other',
  message text NOT NULL DEFAULT '',
  image_url text,
  owner_id text,
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 2. Index for sorting by newest
CREATE INDEX IF NOT EXISTS contact_messages_created_at_idx
  ON public.contact_messages (created_at DESC);

-- 3. Enable RLS (following the same pattern as the other project tables)
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any (to avoid duplicates)
DROP POLICY IF EXISTS "contact_messages_select_policy" ON public.contact_messages;
DROP POLICY IF EXISTS "contact_messages_insert_policy" ON public.contact_messages;
DROP POLICY IF EXISTS "contact_messages_update_policy" ON public.contact_messages;
DROP POLICY IF EXISTS "contact_messages_delete_policy" ON public.contact_messages;

-- Anyone (anonymous users via the anon key) can read all messages.
-- The app's admin panel is gated on the client side (PIN), consistent with
-- how services/categories/slider already behave in this project.
CREATE POLICY "contact_messages_select_policy" ON public.contact_messages
  FOR SELECT USING (true);

-- Anonymous users must be able to submit a new message.
CREATE POLICY "contact_messages_insert_policy" ON public.contact_messages
  FOR INSERT WITH CHECK (true);

-- Allowed so the admin panel can update the status of a message.
CREATE POLICY "contact_messages_update_policy" ON public.contact_messages
  FOR UPDATE USING (true);

-- Allowed so the admin panel can remove a message.
CREATE POLICY "contact_messages_delete_policy" ON public.contact_messages
  FOR DELETE USING (true);