-- ============================================================
-- SQL Migration: جدول تعليقات "تواصل معنا"
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content text NOT NULL DEFAULT '',
  image_url text,
  owner_id text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS comments_created_at_idx
  ON public.comments (created_at DESC);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "comments_select_policy" ON public.comments;
DROP POLICY IF EXISTS "comments_insert_policy" ON public.comments;
DROP POLICY IF EXISTS "comments_update_policy" ON public.comments;
DROP POLICY IF EXISTS "comments_delete_policy" ON public.comments;

-- Everyone can read all comments (public wall, like existing tables in the app).
CREATE POLICY "comments_select_policy" ON public.comments
  FOR SELECT USING (true);

-- Anonymous users must be able to post a comment.
CREATE POLICY "comments_insert_policy" ON public.comments
  FOR INSERT WITH CHECK (true);

CREATE POLICY "comments_update_policy" ON public.comments
  FOR UPDATE USING (true);

CREATE POLICY "comments_delete_policy" ON public.comments
  FOR DELETE USING (true);